---
name: "Deploy"
"on":
  push:
    branches:
    - "main"
concurrency:
  group: "github-pages"
  cancel-in-progress: true
jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Check out repository"
      uses: "actions/checkout@v4"
    - name: "Upload artifact"
      uses: "actions/upload-pages-artifact@v3"
      with:
        path: "docs/"
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    needs: "build"
    permissions:
      pages: "write"
      id-token: "write"
    environment:
      name: "github-pages"
      url: "${{ steps.deploy.outputs.page_url }}"
    steps:
    - name: "Set up GitHub Pages"
      uses: "actions/configure-pages@v5"
    - name: "Deploy to GitHub Pages"
      id: "deploy"
      uses: "actions/deploy-pages@v4"
